config/routes.rb
Rails.application.routes.draw do

  root "pages#home"

  devise_for :users,
              path: '',
              path_names: {sign_in: 'login', sign_out: 'logout', edit: 'profile', sign_up: 'registration'},
              controllers: {omniauth_callbacks: 'omniauth_callbacks'}


  resources :users, only: [:show]

  resources :accommodations, except: [:edit] do
    member do
      get 'listing'
      get 'pricing'
      get 'description'
      get 'photo_upload'
      get 'amenities'
      get 'location'
    end
    resources :photos, only: [:create, :destroy]
      #only allow user to create reservation
    resources :reservations, only: [:create]
  end

  resources :guest_reviews, only: [:create, :destroy]
  resources :host_reviews, only: [:create, :destroy]

  get 'search' => 'page#search'

  #---------PRIVATE MESSAGES-------
  resources :conversations, only: [:index, :create] do
    resources :messages, only: [:index, :create]
  end
end

app/models/accommodation.rb
class Accommodation < ApplicationRecord
  belongs_to :user
  has_many :photos
  has_many :reservations

  has_many :guest_reviews

  geocoded_by :address
  after_validation :geocoder, if: :address_changed?

  validates :land_type, presence: true
  validates :accommodation_type, presence: true

  validates :area, presence: true
  validates :capacity, presence: true

##luke added geocoder for saving location to work##############################
  def geocoder
    puts "----im here"
  end
##

  def cover_photo(size)
    if self.photos.length > 0
      self.photos[0].image.url(size)
    else
      "blank.jpg"
    end
  end

  def average_rating
    # if guest reviews =0, it will just return to 0, otherwise(:) it will just
    # return to average that rounds up to 2 decimals
    guest_reviews.count == 0 ? 0 : guest_reviews.average(:star).round(2).to_i
  end


end

app/controllers/accommodations_controller.rb
class AccommodationsController < ApplicationController

  #before you run any action below , just run set_accommodation first
  before_action :set_accommodation, except: [:index, :new, :create]

  # we need user to login for updating listing/pricing/description
  # except show, you can view the accommodation without logging in, its public to everyone
  before_action :authenticate_user!, except: [:show]

  before_action :is_authorised, only: [:listing, :pricing, :description, :photo_upload, :amenities, :location, :update]

  def index
    # at index we want to list all the accommodations belong to the user,
    # so we create a new variable name accommodations
    #so .accommodations returns all the accommods onto this user
    @accommodations = current_user.accommodations
  end

  def new
    # when a user open a new page, it allows user to craete a new accommodation
    @accommodation = current_user.accommodations.new
  end

  def create
    # for create, we going to pass the accommods params
    @accommodation = current_user.accommodations.build(accommodation_params)
    if @accommodation.save
      redirect_to listing_accommodation_path(@accommodation), notice: "Saved..."
    else
      flash[:alert] = "Something went wrong..."
      render :new
    end
  end

  def listing
    # To be able to edit/update the listing, we need to know which
    # accommodation we are working on, first we have the accommod id as paramters.
    # we look inside the database, the accommod table to find the id and we return
    # to the variable. (DO the same for the other actions)
    set_accommodation
  end

  def show
    @photos = @accommodation.photos
  end

  def pricing
    set_accommodation
  end

  def description
    set_accommodation
  end

  def photo_upload
    @photos = @accommodation.photos
  end

  def amenities
  end

  def location
  end

  def update
    if @accommodation.update(accommodation_params)
      flash[:notice] = "Saved..."
    else
      flash[:alert] = "Something went wrong..."
    end
      redirect_back(fallback_location: request.referer)
  end


    # To be able to edit/update the listing, we need to know which
    # accommodation we are working on, first we have the accommod id as paramters.
    # we look inside the database, the accommod table to find the id and we return
    # to the variable. (DO the same for the other actions)
  private
    def set_accommodation
      @accommodation = Accommodation.find(params[:id])
    end

    # this redirects users back to the homepage so they cant change the information
    def is_authorised
      redirect_to root_path, alert: "You don't have permission" unless current_user.id == @accommodation.user_id
    end

    def accommodation_params
      # whenever you want to crete/ update accommodation, you need to permit which attribute you
      # allow users to update/edit/create
      params.require(:accommodation).permit(:land_type, :accommodation_type, :area, :capacity,
      :listing_name, :summary, :address, :is_tv, :is_kitchen, :is_air, :is_heating, :is_internet,
      :price, :active)
    end
end

app/helpers/accommodation_helper.rb
module AccommodationHelper
end

app/views/accommodations/_accommodation_menu.html.erb
<ul class="sidebar-list">
<li class="sidebar-item">
  <%= link_to "Listing", listing_accommodation_path, class: "sidebar-link active" %>
  <span class="pull-right text-babu"><i class="fa fa-check"></i></span>
</li>
<li class="sidebar-item">
  <%= link_to "Pricing", pricing_accommodation_path, class: "sidebar-link active" %>
  <% if !@accommodation.price.blank? %>
    <span class="pull-right text-babu"><i class="fa fa-check"></i></span>
  <% end %>
</li>
<li class="sidebar-item">
  <%= link_to "Description", description_accommodation_path, class: "sidebar-link active" %>
  <% if !@accommodation.listing_name.blank? %>
    <span class="pull-right text-babu"><i class="fa fa-check"></i></span>
  <% end %>
</li>
<li class="sidebar-item">
  <%= link_to "Photos", photo_upload_accommodation_path, class: "sidebar-link active" %>
  <% if !@accommodation.photos.blank? %>
    <span id="photo_check" class="pull-right text-babu"><i class="fa fa-check"></i></span>
  <% end %>
</li>
<li class="sidebar-item">
  <%= link_to "Amenities", amenities_accommodation_path, class: "sidebar-link active" %>
  <span class="pull-right text-babu"><i class="fa fa-check"></i></span>
</li>
<li class="sidebar-item">
  <%= link_to "Location", location_accommodation_path, class: "sidebar-link active" %>
  <% if !@accommodation.address.blank? %>
    <span class="pull-right text-babu"><i class="fa fa-check"></i></span>
  <% end %>
</li>
</ul>
<hr/>

<% is_ready = !@accommodation.active && !@accommodation.price.blank? && !@accommodation.listing_name.blank? && !@accommodation.photos.blank? && !@accommodation.address.blank? %>

<%= form_for @accommodation do |f| %>
<%= f.hidden_field :active, value: true %>
<%= f.submit "Publish", id: "publish_button", class: "btn btn-normal btn-block", disabled: !is_ready %>
<% end %>

app/views/accommodations/_accommodations_list.html.erb
<div class= "row">
  <% accommodations.each do |accommodation| %>
      <div class="col-md-4">
        <div class="panel panel-default">
          <div class="panel-heading preview">
            <%= image_tag accommodation.cover_photo(:medium) %>
          </div>
          <div class="panel-body">
            <%= link_to accommodation.listing_name, accommodation %><br/>
            $<%= accommodation.price %> - <%= accommodation.land_type %> - <%= pluralize(accommodation.area, "area") %>
            <div id="star_<%= accommodation.id %>"></div> <%= pluralize(accommodation.average_rating, "review") %>
          </div>
        </div>
      </div>

    <script>
      $('#star_<%= accommodation.id %>').raty({
        path: '/assets',
        readOnly: true,
        score: <%= accommodation.average_rating %>
      });
    </script>
<% end %>

app/views/accommodations/amenities.html.erb
<div class="row">

  <div class="col-md-3"
  <%= render 'accommodation_menu' %>

  </div>

  <div class="col-md-9">
    <div class="panel panel-default">

      <div class="panel-heading">
        Amenities
      </div>

      <div class="panel-body">
        <div class="container">
          <%= form_for @accommodation do |f| %>

          <div class="row form-group">
            <div class="colw-md-4">
              <%= f.check_box :is_tv %> TV
            </div>

            <div class="colw-md-4">
              <%= f.check_box :is_kitchen %> Kitchen
            </div>

            <div class="colw-md-4">
              <%= f.check_box :is_internet %> Internet
            </div>
          </div>

          <div class="row form-group">
            <div class="colw-md-4">
              <%= f.check_box :is_heating %> Heating
            </div>

            <div class="colw-md-4">
              <%= f.check_box :is_air %> Air Conditioning
            </div>

          </div>
          <br></br>

          <div class="text-center">
            <%= f.submit "Save", class: "btn btn-form" %>

          </div>

          <% end %>
        </div>
      </div>

    </div>
  </div>

</div>

app/views/accommodations/create.html.erb
<h1>Accommodation#create</h1>
<p>Find me in app/views/accommodation/create.html.erb</p>

app/views/accommodations/description.html.erb
<div class="row">

  <div class="col-md-3"
  <%= render 'accommodation_menu' %>

  </div>

  <div class="col-md-9">
    <div class="panel panel-default">

      <div class="panel-heading">
        Description
      </div>

      <div class="panel-body">
        <div class="container">
          <%= form_for @accommodation do |f| %>

          <div class="row">
            <div class="form-group">
              <label>Listing name</label>
              <%= f.text_field :listing_name, placeholder: "What is your listing name?", class:"form-control", required: true %>
            </div>
          </div>

          <div class="row">
            <div class="form-group">
              <label>Summary</label>
              <%= f.text_area :summary, rows: 5, placeholder: "Summary of your accommodation", class:"form-control", required: true %>
            </div>
          </div>

          <div class="text-center">
            <%= f.submit "Save", class: "btn btn-form" %>
          </div>

          <% end %>
        </div>
      </div>

    </div>
  </div>

</div>

app/views/accommodations/index.html.erb
<div class="row">
  <div class="col-md-3">
    <ul class="sidebar-list">
      <li class="sidebar-item"><%= link_to "Your Listings", accommodations_path, class: "sidebar-link active" %></li>
    </ul>
  </div>
  <div class="col-md-9">
    <div class="panel panel-default">
      <div class="panel-heading">
        Listings
      </div>
      <div class="panel-body">

        <% @accommodations.each do |accommodation| %>
          <div class="row">
            <div class="col-md-2">
              <%= image_tag accommodation.cover_photo(:thumb) %>
            </div>
            <div class="col-md-7">
              <h4><%= accommodation.listing_name %></h4>
            </div>
            <div class="col-md-3 right">
              <%= link_to "Update", listing_accommodation_path(accommodation), class: "btn btn-form" %>
            </div>
          </div>
          <hr/>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/accommodations/listing.html.erb
<div class="row">

  <div class="col-md-3"
  <%= render 'accommodation_menu' %>

  </div>

  <div class="col-md-9">
    <div class="panel panel-default">

      <div class="panel-heading">
        Listing
      </div>

      <div class="panel-body">
        <div class="container">
          <%= form_for @accommodation do |f| %>

          <div class="row">
            <div class="col-md-4 select">
              <div class="form-group">
                <label> Land type</label>
                <%= f.select :land_type, [["Oceanfront", "Oceanfront"], ["Mountains", "Mountains"], ["Vineyards", "Vineyards"], ["Hiking Getaways", "Hiking Getaways"], ["Farms", "Farms"]],
                              id: "land_type", prompt: "Select...", class: "form-control" %>
              </div>
            </div>

            <div class="col-md-4 select">
              <div class="form-group">
                <label> Accommodation type</label>
                <%= f.select :accommodation_type, [["Huts", "Huts"], ["Villas", "Villas"], ["Cabins", "Cabins"], ["Tents", "Tents"], ["Treehouses", "Treehouses"], ["Pods", "Pods"]],
                id: "accommodation_type", prompt: "Select...", class: "form-control" %>
              </div>
            </div>

            <div class="col-md-4 select">
              <div class="form-group">
                <label> Area </label>
                <%= f.select :area, [["Chocolate Factory", "Chocolate Factory"], ["Wine Tasting", "Wine Tasting"], ["Bush Walking", "Bushwalking"]],
                              id: "area", prompt: "Select...", class: "form-control" %>
              </div>
            </div>

            <div class="col-md-4 select">
              <div class="form-group">
                <label> Maximum Capacity </label>
                <%= f.select :capacity, [["2 people", "2 people"],["5 people", "5 people"], ["10 people", "10 people"], ["15 people", "15 people"]],
                              id: "capacity", prompt: "Select...", class: "form-control" %>
              </div>
            </div>
          </div>

          <div>
            <%= f.submit "Save", class: "btn btn-normal" %>
          </div>

          <% end %>

        </div>
      </div>

    </div>
  </div>

</div>

app/views/accommodations/location.html.erb
<div class="row">

  <div class="col-md-3"
  <%= render 'accommodation_menu' %>

  </div>

  <div class="col-md-9">
    <div class="panel panel-default">

      <div class="panel-heading">
        Location
      </div>

      <div class="panel-body">
        <div class="container">
          <%= form_for @accommodation do |f| %>

          <div class="row">
            <div class="form-group">
              <label>Address</label>
              <%= f.text_field :address, placeholder: "What is your address?", class:"form-control", required: true %>
            </div>
          </div>

          <div class="text-center">
            <%= f.submit "Save", class: "btn btn-form" %>
          </div>

          <% end %>

        </div>
      </div>

    </div>
  </div>

</div>

app/views/accommodations/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    Create your beautiful place
  </div>
  <div class="panel-body">
    <div class="container">

      <%= form_for @accommodation do |f| %>

        <div class="row">

          <div class="col-md-4 select">
            <div class="form-group">
              <label>Land Type</label>
                <%= f.select :land_type, [["Oceanfront", "Oceanfront"], ["Mountains", "Mountains"], ["Vineyards", "Vineyards"], ["Hiking Getaways", "Hiking Getaways"], ["Farms", "Farms"]],
                              id: "land_type", prompt: "Select...", class: "form-control" %>
            </div>
          </div>

          <div class="col-md-4 select">
            <div class="form-group">
              <label>Accommodation Type</label>
              <%= f.select :accommodation_type, [["Huts", "Huts"], ["Villas", "Villas"], ["Cabins", "Cabins"], ["Tents", "Tents"], ["Treehouses", "Treehouses"], ["Pods", "Pods"]],
                            id: "accommodation_type", prompt: "Select...", class: "form-control" %>
            </div>
          </div>

          <div class="col-md-4 select">
            <div class="form-group">
              <label>Area</label>
              <%= f.select :area, [["Chocolate Factory", "Chocolate Factory"], ["Wine Tasting", "Wine Tasting"], ["Bush Walking", "Bushwalking"]],
                            id: "area", prompt: "Select...", class: "form-control" %>
            </div>
          </div>

          <div class="col-md-4 select">
            <div class="form-group">
              <label>Maximum Capacity</label>
              <%= f.select :capacity, [["2 people", "2 people"],["5 people", "5 people"], ["10 people", "10 people"], ["15 people", "15 people"]],
              id: "capacity", prompt: "Select...", class: "form-control" %>
            </div>
          </div>

        </div>

        <div><%= f.submit "Create My Place", class: "btn btn-normal" %></div>

      <% end %>

    </div>
  </div>
</div>

app/views/accommodations/photo_upload.html.erb
<div class= "row">

  <div class= "col-md-3"
  <%= render 'accommodation_menu' %>

  </div>

  <div class= "col-md-9">
    <div class="panel panel-default">

      <div class= "panel-heading">
        Photos
      </div>

      <div class= "panel-body">
        <div class= "container">
          <div class= "row">
            <div class= "col-md-offset-3 col-md-6">
              <!-- PHOTOS UPLOAD GOES HERE -->

              <%= form_for @accommodation, url: accommodation_photos_path(@accommodation), method: 'post', html:{multipart: true} do |f| %>
                <div class= "row">
                  <div class= "form-group">
                    <span class= "btn  btn-default btn-file text-babu">
                      <i class="fa fa-upload" aria-hidden="true"></i>Select Photos
                      <%= file_field_tag "images[]", type: :file, multiple: true %>
                    </span>
                  </div>
                </div>

                <div class="text-center">
                    <%= f.submit "Add Photos", class: "btn btn-form" %>

                </div>

                <% end %>
              </div>

            </div>
          </div id="photos"><%= render 'photos/photos_list' %></div>

        </div>
      </div>

    </div>
  </div>

</div>

app/views/accommodations/pricing.html.erb
<div class="row">

  <div class="col-md-3"
  <%= render 'accommodation_menu' %>

  </div>

  <div class="col-md-9">
    <div class="panel panel-default">

      <div class="panel-heading">
        Pricing
      </div>

      <div class="panel-body">
        <div class="container">
          <%= form_for @accommodation do |f| %>

          <div class="row">
            <div class="form-group">
              <label>Price</label>
              <%= f.text_field :price, placeholder: "e.g. $100", class:"form-control", required: true %>
            </div>
          </div>

          <div class="text-center">
            <%= f.submit "Save", class: "btn btn-form" %>
          </div>

          <% end %>
        </div>
      </div>

    </div>
  </div>

</div>

app/views/accommodations/show.html.erb
<!-- Image -->
<div class="row">
  <div class="col-md-12">
    <%= image_tag @accommodation.cover_photo(nil), width: "100%" %>
  </div>
</div>
<br/>

<div class="row">

  <!-- LEFT PANEL -->
  <div class="col-md-8">

    <!-- Listing Name -->
    <div class="row">
      <div class="col-md-8">
        <h1><%= @accommodation.listing_name %></h1>
        <%= @accommodation.address %>
      </div>
      <div class="col-md-4 text-center">
        <%= image_tag avatar_url(@accommodation.user), class: "img-circle avatar-large" %><br/><br/>
        <%= @accommodation.user.fullname %>
      </div>
    </div>
    <hr/>

    <!-- accommodation Info -->
    <div class="row text-babu">
      <div class="row text-center row-space-1">
        <div class="col-md-3">
          <i class="fa fa-home fa-2x"></i>
        </div>
        <div class="col-md-3">
          <i class="fa fa-user-circle-o fa-2x"></i>
        </div>
        <div class="col-md-3">
          <i class="fa fa-bed fa-2x"></i>
        </div>
        <div class="col-md-3">
          <i class="fa fa-bath fa-2x"></i>
        </div>
      </div>

      <div class="row text-center">
        <div class="col-md-3"><%= @accommodation.land_type %></div>
        <div class="col-md-3"><%= pluralize(@accommodation.area, "Area") %></div>
        <div class="col-md-3"><%= pluralize(@accommodation.capacity, "Capacity") %></div>
      </div>

    </div>
    <hr/>

    <!-- About -->
    <div class="row">
      <div class="col-md-12">
        <h3>About This Listing</h3>
        <p><%= @accommodation.summary %></p>
      </div>
    </div>
    <hr/>



    <!-- Carousel from bootstrap: image slides: www.w3schools.com/bootstrap/bootstrap_carousel.asp-->
    <div class="row">

      <% if @photos.length > 0 %>
          <div id="myCarousel" class="carousel slide" data-ride="carousel">
          <!-- Indicators -->
          <ol class="carousel-indicators">
            <% @photos.each do |photo| %>
                <li data-target="#myCarousel" data-slide-to="<%= photo.id %>"></li>
            <% end %>
          </ol>

          <!-- Wrapper for slides -->
          <div class="carousel-inner">
            <% @photos.each do |photo| %>
                <div class="item <%= 'active' if photo.id == @photos[0].id %>">
                  <%= image_tag photo.image.url() %>
                </div>
            <% end %>
          </div>

          <!-- Left and right controls -->
          <a class="left carousel-control" href="#myCarousel" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="right carousel-control" href="#myCarousel" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>
      <% end %>

    </div>
    <hr/>

    <!-- GOOGLE MAP -->
    <div class="row">

      <div id="map" style="width: 100%; height: 400px"></div>

      <script src="https://maps.googleapis.com/maps/api/js"></script>
      <script>
          function initialize() {
            var location = {lat: <%= @accommodation.latitude %>, lng: <%= @accommodation.longitude %>};
            var map = new google.maps.Map(document.getElementById('map'), {
              center: location,
              zoom: 14
            });

            var marker = new google.maps.Marker({
              position: location,
              map: map
            });

            var infoWindow = new google.maps.InfoWindow({
              content: '<div id="content"><%= image_tag @accommodation.cover_photo(:medium) %></div>'
            });

            infoWindow.open(map, marker);
          }

          google.maps.event.addDomListener(window, 'load', initialize);
      </script>

    </div>
    <hr/>

    <!-- Reference: https://developers.google.com/maps/documentation/javascript/examples/infowindow-simple -->

    <!-- maybe create a random suggestion later when i have time -->

    <!-- RIGHT PANEL -->
    <div class="col-md-4">
      <!-- Reservation Form -->
      <%= render partial: 'reservations/form', locals: {accommodation: @accommodation} %>
    </div>
  </div>

app/views/accommodations/update.html.erb
<h1>Accommodation#update</h1>
<p>Find me in app/views/accommodation/update.html.erb</p>