config/routes.rb
Rails.application.routes.draw do

  root "pages#home"

  devise_for :users,
              path: '',
              path_names: {sign_in: 'login', sign_out: 'logout', edit: 'profile', sign_up: 'registration'},
              controllers: {omniauth_callbacks: 'omniauth_callbacks'}


  resources :users, only: [:show]

  resources :accommodations, except: [:edit] do
    member do
      get 'listing'
      get 'pricing'
      get 'description'
      get 'photo_upload'
      get 'amenities'
      get 'location'
    end
    resources :photos, only: [:create, :destroy]
      #only allow user to create reservation
    resources :reservations, only: [:create]
  end

  resources :guest_reviews, only: [:create, :destroy]
  resources :host_reviews, only: [:create, :destroy]

  get 'search' => 'page#search'

  #---------PRIVATE MESSAGES-------
  resources :conversations, only: [:index, :create] do
    resources :messages, only: [:index, :create]
  end
end

app/views/shared/_navbar.html.erb
<!-- Static navbar -->


<nav class="navbar navbar-light" style="background-color: #e3f2fd;">

  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">CampBnB</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <% if (!user_signed_in?) %>
        <li><%= link_to "Login", new_user_session_path %></li>
        <li><%= link_to "Sign Up", new_user_registration_path %></li>

        <% else %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">


            <%= image_tag avatar_url(current_user), class: "image_circle avatar_small" %>&nbsp;
            <%= current_user.fullname %><span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Manage Listing", accommodations_path %></li>
            <li><%= link_to "List Your Space", new_accommodation_path %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
            <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
          </ul>
        </li>
        <% end %>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

<% if (user_signed_in?) && !current_page?(root_path) && !current_page?("/rooms/#{params[:id]}")%>
    <nav class="navbar navbar-default" style="background-color: #565A5C">
      <div class="container">
        <ul class="nav navbar-nav">
          <li <% if current_page?(accommodations_path) %> class="active" <% end %> ><%= link_to "Manage Listings", accommodations_path %></li>
          <li <% if current_page?(conversations_path) %> class="active" <% end %> ><%= link_to "Messages", conversations_path %></li>
        </ul>
      </div>
    </nav>
<% end %>