config/routes.rb
Rails.application.routes.draw do

  root "pages#home"

  devise_for :users,
              path: '',
              path_names: {sign_in: 'login', sign_out: 'logout', edit: 'profile', sign_up: 'registration'},
              controllers: {omniauth_callbacks: 'omniauth_callbacks'}


  resources :users, only: [:show]

  resources :accommodations, except: [:edit] do
    member do
      get 'listing'
      get 'pricing'
      get 'description'
      get 'photo_upload'
      get 'amenities'
      get 'location'
    end
    resources :photos, only: [:create, :destroy]
      #only allow user to create reservation
    resources :reservations, only: [:create]
  end

  resources :guest_reviews, only: [:create, :destroy]
  resources :host_reviews, only: [:create, :destroy]

  get 'search' => 'page#search'

  #---------PRIVATE MESSAGES-------
  resources :conversations, only: [:index, :create] do
    resources :messages, only: [:index, :create]
  end
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :accommodation

  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController

  def create
    @accommodation = Accommodation.find(params[:accommodation_id])

    if params[:images]
      params[:images].each do |img|
        @accommodation.photos.create(image: img)
      end

      @photos = @accommodation.photos
      redirect_back(fallback_location: request.referer, notice: "Saved...")
    end
  end

#delete photo upload
  def destroy
#this is going to find the photos that you want base on id
    @photo = Photo.find(params[:id])
    @accommodation = @photo.accommodation

#and then delete it
    @photo.destroy
#and then guess all of the remains of those belong to the id
    @photos = Photo.where(accommodation_id: @accommodation_id)

#returns to/render destroy.js.erb
    respond_to :js

  end
end

app/views/photos/_photos_list.html.erb
<% if @photos.count > 0 %>
  <br/><br/>

  <div class="row">
    <% @photos.each do |photo| %>
      <div class="col-md-4">
        <div class="panel panel-default">
          <div class="panel-heading preview">
            <%= image_tag photo.image.url() %>
          </div>
          <div class="panel-body">
            <span class="pull-right">
              <%= link_to accommodation_photo_path(photo.accommodation_id, photo), remote: true, method: :delete, data: {confirm: "Are you sure?"} do %>
                <i class="fa fa-trash-o fa-lg" aria-hidden="true"></i>
              <% end %>
            </span>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/photos/destroy.js.erb
 // it just re-render the whole list
$('#photos').html("<%= j render 'photos_list' %>")